# Site settings
title: Exotic Stylish
email: info@exotic-stylish.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Exotic stylish leathers
baseurl: "exotic-stylish"
url: "http://exotic-stylish.com/"

# Build settings
markdown: kramdown

scope:
      path: "products"
      type: "posts"
