---
title: Exotic Stylish
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@exotic-stylish.co.uk
description: 'Exotic stylish leathers

'
baseurl: ''
url: http://exotic-stylish.com/
markdown: kramdown
scope:
  path: products
  type: posts
